version: '3.8'

services:
  movies-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/movies_api
    links:
      - postgres
    environment:
      DB_NAME: movies
      DB_USER: postgres
      DB_PASSWORD: pgsecret
      DB_HOST: postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/movies_api
    depends_on:
      - postgres

  #postgres
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgsecret
      POSTGRES_DB: movies
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}